### ISSUE TITLE
mmt make alltex no longer works

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#96] opened 2015-11-21 15:55 UTC
I get (on localmh/MathHub)
```
Michaels-MBP:MathHub kohlhase$ mrbuild alltex
alltex-result: success /Users/kohlhase/localmh/MathHub/BaseMH/physics/source/units/en/all.tex
alltex-result: success /Users/kohlhase/localmh/MathHub/BaseMH/physics/source/units/fragments/all.tex
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:151)
	at info.kwarc.mmt.stex.AllTeX.info$kwarc$mmt$stex$AllTeX$$buildDir(LaTeXML.scala:52)
	at info.kwarc.mmt.stex.AllTeX$$anonfun$update$4.apply(LaTeXML.scala:35)
	at info.kwarc.mmt.stex.AllTeX$$anonfun$update$4.apply(LaTeXML.scala:34)
	at info.kwarc.mmt.api.archives.WritableArchive.traverse(Archive.scala:106)
	at info.kwarc.mmt.api.archives.WritableArchive.info$kwarc$mmt$api$archives$WritableArchive$$recurse$1(Archive.scala:98)
	at info.kwarc.mmt.api.archives.WritableArchive$$anonfun$4.apply(Archive.scala:105)
	at info.kwarc.mmt.api.archives.WritableArchive$$anonfun$4.apply(Archive.scala:105)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at info.kwarc.mmt.api.archives.WritableArchive.traverse(Archive.scala:105)
	at info.kwarc.mmt.stex.AllTeX.update(LaTeXML.scala:32)
	at info.kwarc.mmt.api.archives.BuildTarget.apply(BuildTarget.scala:73)
	at info.kwarc.mmt.api.frontend.Controller$$anonfun$buildFilesAction$1$$anonfun$apply$14.apply(Controller.scala:548)
	at info.kwarc.mmt.api.frontend.Controller$$anonfun$buildFilesAction$1$$anonfun$apply$14.apply(Controller.scala:536)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at info.kwarc.mmt.api.frontend.Controller$$anonfun$buildFilesAction$1.apply(Controller.scala:535)
	at info.kwarc.mmt.api.frontend.Controller$$anonfun$buildFilesAction$1.apply(Controller.scala:528)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at info.kwarc.mmt.api.frontend.Controller.buildFilesAction(Controller.scala:528)
	at info.kwarc.mmt.api.frontend.Controller.handle(Controller.scala:660)
	at info.kwarc.mmt.api.frontend.Controller.handleLine(Controller.scala:484)
	at info.kwarc.mmt.api.frontend.Shell$$anonfun$main$3.apply(Shell.scala:95)
	at info.kwarc.mmt.api.frontend.Shell$$anonfun$main$3.apply(Shell.scala:95)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at info.kwarc.mmt.api.frontend.Shell.main(Shell.scala:95)
	at info.kwarc.mmt.api.frontend.Run.main(Shell.scala)
```

**Comment by cmaeder** [comment] 2015-11-23 10:05
I could not reproduce the `assertion failed` in `BaseMH/physics` but in `MiKoMH/ACS`. However, it succeeded within `MiKoMH/ACS/source/cfl/en` (because some dependencies are then ignored).

You could try, if it works for you in `BaseMH/physics/source/units/fragments`, too. (The bug is - hopefully - fixed in svn, however, due to another bug in svn, it is not merged to `gh-pages`, yet.)

**Closed by cmaeder** 2015-11-23 10:05 UTC
Labels: bug
